{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  endpoints:
    - port: {{ .Values.serviceMonitor.port }}
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.path }}
{{- end }}
